apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: semaphore-agent-scale-down
  namespace: semaphore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: semaphore-agent
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: External
      external:
        metric:
          name: occupied_agents_percentage
        target:
          type: Value
          value: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 20
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 10
    scaleUp:
      selectPolicy: Disabled